### ISSUE TITLE
Actividad 7 - Juicio experto y costos

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-awua-de-limon#1]
[Practica 7.pdf](https://github.com/user-attachments/files/17528855/Practica.7.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by Luz1727** [comment]
calificacion: 20% 
Buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
